config/routes.rb
Rails.application.routes.draw do
  resources :job_categories
  resources :vacancies

  root 'job_categories#index'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
end

app/models/employer.rb
class Employer < ActiveRecord::Base
end

app/models/job_category.rb
class JobCategory < ActiveRecord::Base
  has_many :vacancies
  validates :name, :presence => true
end

app/models/vacancy.rb
class Vacancy < ActiveRecord::Base
  belongs_to :job_category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/job_categories_controller.rb
class JobCategoriesController < ApplicationController
  before_action :set_job_category, only: [:show, :edit, :update, :destroy]

  # GET /job_categories
  # GET /job_categories.json
  def index
    @job_categories = JobCategory.all
  end

  # GET /job_categories/1
  # GET /job_categories/1.json
  def show
  end

  # GET /job_categories/new
  def new
    @job_category = JobCategory.new
  end

  # GET /job_categories/1/edit
  def edit
  end

  # POST /job_categories
  # POST /job_categories.json
  def create
    @job_category = JobCategory.new(job_category_params)

    respond_to do |format|
      if @job_category.save
        format.html { redirect_to @job_category, notice: 'Job category was successfully created.' }
        format.json { render :show, status: :created, location: @job_category }
      else
        format.html { render :new }
        format.json { render json: @job_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /job_categories/1
  # PATCH/PUT /job_categories/1.json
  def update
    respond_to do |format|
      if @job_category.update(job_category_params)
        format.html { redirect_to @job_category, notice: 'Job category was successfully updated.' }
        format.json { render :show, status: :ok, location: @job_category }
      else
        format.html { render :edit }
        format.json { render json: @job_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_categories/1
  # DELETE /job_categories/1.json
  def destroy
    @job_category.destroy
    respond_to do |format|
      format.html { redirect_to job_categories_url, notice: 'Job category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job_category
      @job_category = JobCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_category_params
      params.require(:job_category).permit(:name)
    end
end

app/controllers/vacancies_controller.rb
class VacanciesController < ApplicationController
  def index
    @vacancies = Vacancy.all
  end

  def new
    @category = JobCategory.all
    @vacancy = Vacancy.new
  end

  def create
    @vacancy = Vacancy.new(vacancy_params)
    if @vacancy.save
      flash[:notice] = "New Vacancy has been posted successfully"
      redirect_to @vacancy
    else
      redirect_to 'new'
    end
  end

  def show
    @vacancy = Vacancy.find(params[:id])
  end

  def edit
    @category = JobCategory.all
    @vacancy = Vacancy.find(params[:id])
  end

  def update
    @vacancy = Vacancy.find(params[:id])
    if @vacancy.update(vacancy_params)
      flash[:notice] = "Updated successfully"
      redirect_to @vacancy
    else
      render edit
    end
  end

  def destroy
    Vacancy.find(params[:id]).destroy
    flash[:notice] = "Vacancy deleted successfully."
    redirect_to root_path
  end

  private

  def vacancy_params
    params.require(:vacancy).permit(:title, :no_of_jobs, :description,
    :job_type, :academic_requirements, :experience, :additional_requirements,
    :job_location, :salary, :benefits, :job_source, :job_category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/job_categories_helper.rb
module JobCategoriesHelper
end

app/helpers/vacancies_helper.rb
module VacanciesHelper
end

app/views/job_categories/_form.html.erb
<%= form_for(@job_category) do |f| %>
  <% if @job_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job_category.errors.count, "error") %> prohibited this job_category from being saved:</h2>

      <ul>
      <% @job_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/job_categories/edit.html.erb
<h1>Editing job_category</h1>

<%= render 'form' %>

<%= link_to 'Show', @job_category %> |
<%= link_to 'Back', job_categories_path %>

app/views/job_categories/index.html.erb
<h1>Listing job_categories</h1>

<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @job_categories.each do |job_category| %>
      <tr>
        <td><%= link_to  "#{job_category.name} (#{job_category.vacancies.count})", job_category %></td>
        <td><%= link_to 'Edit', edit_job_category_path(job_category) %></td>
        <td><%= link_to 'Destroy', job_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job category', new_job_category_path %>

app/views/job_categories/new.html.erb
<h1>New job_category</h1>

<%= render 'form' %>

<%= link_to 'Back', job_categories_path %>

app/views/job_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @job_category.name %>
</p>
<% if @job_category.vacancies.count > 0 %>
<p>Total <%= pluralize(@job_category.vacancies.count, 'job')  %></p>
<table class="table">
  <tr>
  <th>Job Title</th>
    <th>Academic Qualification</th>
    <th>Experience</th>
  </tr>
  <% @job_category.vacancies.each do |vacancy| %>
  <tr>
    <td><%= link_to vacancy.title, vacancy %></td>
    <td><%= vacancy.academic_requirements %></td>
    <td><%= vacancy.experience %></td>
  </tr>
      <% end %>
</table>
    <% else %>
    <p><strong>No job found for this categroy</strong></p>
   <% end %>
<%= link_to 'Edit Category', edit_job_category_path(@job_category) %> |
<%= link_to 'Back', job_categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RecruitmentSystem</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(object.errors.count, "error") %>
      </div>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li>* <%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/vacancies/_form.html.erb
<div class="row">
  <div class="col-lg-8 col-lg-offset-3">
  <%= form_for @vacancy, :html => {class: "form-horizontal"} do |f|%>
      <%= render 'shared/error_messages', object: f.object %>
        <p><strong>Category</strong>
          <%= f.select :job_category_id, @category.all.collect{|p| [ p.name, p.id ] },
                       { prompt: "Please Select"} %>
        </p>
        <p>
          <%= f.label :title, "Job Title" %>
          <%= f.text_field :title %>
        </p>
        <p>
          <%= f.label :no_of_jobs, "No. of Vacancies" %>
          <%= f.text_field :no_of_jobs %>
        </p>
        <p>
          <%= f.label :description, "Job Descriptions/Responsibilities"%>
          <%= f.text_area :description %>
        </p>
        <p>
          <%= f.label :academic_requirements, "Academic Requiremnts" %>
          <%= f.text_area :academic_requirements %>
        </p>

        <p>
          <%= f.label :experience, "Experience Requirements" %>
          <%= f.text_area :experience %>
        </p>
        <p>
          <%= f.label :job_type, "Job Nature" %>
          <%= f.text_field :job_type %>
        </p>
        <p>
          <%= f.label :benefits, "Benefits" %>
          <%= f.text_area :benefits %>
        </p>
        <p>
          <%= f.label :salary, "Salary Ranges" %>
          <%= f.text_field :salary %>
        </p>
        <p>
          <%= f.label :job_location %>
          <%= f.text_field :job_location %>
        </p>
        <p>
          <%= f.label :job_source %>
          <%= f.text_field :job_source %>
        </p>
        <p>
          <%= f.submit %>
        </p>
  <% end %>
   </div>
</div>

app/views/vacancies/edit.html.erb
<h2>Update vacancy</h2>
<%= render 'form' %>

app/views/vacancies/index.html.erb
<div class="container">
<h1>Job Lists</h1>

  <table class="table table-striped table-bordered table-hover">
    <tr>

      <thead>
         <th>Job Title</th>
         <th>Academic Requirements</th>
         <th>Experience Requirements</th>
      </thead>
    </tr>
<% @vacancies.each do |vacancy| %>
     <tbody>
     <tr>
  <td><%= link_to vacancy.title, vacancy %></td>
    <td>
      <%= vacancy.academic_requirements %>
    </td>
    <td>
      <%= vacancy.experience %>
    </td>
     </tr>
     </tbody>
<% end %>
  </table>
</div>

app/views/vacancies/new.html.erb
<h1>Post New Vacancy</h1>
<%= render 'form' %>

app/views/vacancies/show.html.erb
<h2>Job Details:</h2>
    <h2>Job Title:</h2>
    <h3><%= @vacancy.title %></h3>

    <p>
      <h3>Job Description/Responsibilities</h3>
      <%= @vacancy.description %>
    </p>
    <p>
<h3>Academic Requirements</h3>
      <%= @vacancy.academic_requirements %>
    </p>
    <p>
<h3>Experience Requirements:</h3>
      <%= @vacancy.experience %>
    </p>
    <p>
<h3>Additional job requirements:</h3>
      <%= @vacancy.additional_requirements %>
    </p>
    <p>
<h3>Job Nature:</h3>
      <%= @vacancy.job_type %>
    </p>
    <p>
<h3>Benefits:</h3>
      <%= @vacancy.benefits %>
    </p>
    <p>
<h3>Job Location:</h3>
      <%= @vacancy.job_location %>
    </p>
    <p>
<h3>JobSource</h3>
      <%= @vacancy.job_source %>
    </p>
    <p><strong>Job posting date:</strong>
       <%= time_ago_in_words (@vacancy.created_at) %> ago
    </p>
<p><%=link_to "Edit", edit_vacancy_path %>  |  <%= link_to "delete", @vacancy, method: :delete, data: { confirm: "You sure?" } %></p>